# Shell variables
# Generated by 'wal'
wallpaper="/home/notscripter/dotfiles/hypr/background.jpg"

# Special
background='#170a15'
foreground='#c5c1c4'
cursor='#c5c1c4'

# Colors
color0='#170a15'
color1='#A6416D'
color2='#69388F'
color3='#993B8C'
color4='#AC4798'
color5='#D154A5'
color6='#DA69D2'
color7='#c5c1c4'
color8='#6d5969'
color9='#A6416D'
color10='#69388F'
color11='#993B8C'
color12='#AC4798'
color13='#D154A5'
color14='#DA69D2'
color15='#c5c1c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
