# pywal theme for ghostty

background = 170a15
foreground = c5c1c4
cursor-color = c5c1c4
selection-background = c5c1c4
selection-foreground = 170a15

palette = 0=#170a15
palette = 1=#A6416D
palette = 2=#69388F
palette = 3=#993B8C
palette = 4=#AC4798
palette = 5=#D154A5
palette = 6=#DA69D2
palette = 7=#c5c1c4
palette = 8=#6d5969
palette = 9=#A6416D
palette = 10=#69388F
palette = 11=#993B8C
palette = 12=#AC4798
palette = 13=#D154A5
palette = 14=#DA69D2
palette = 15=#c5c1c4
