[General]
background=/home/notscripter/.config/themes/background.jpg

# Material You-like colors (we can refine these)
primaryColor=#daa270
accentColor=#cc8a59
backgroundColor=#1A1C18
autoColor=false
use24HourClock=true
textColor=#E3E3DC

# Font settings
fontFamily=FlexRounded
fontSize=16
