--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/notscripter/dotfiles/hypr/background.png"

-- Special
background="#170a15"
foreground="#c5c1c4"
cursor="#c5c1c4"

-- Colors
color0="#170a15"
color1="#A6416D"
color2="#69388F"
color3="#993B8C"
color4="#AC4798"
color5="#D154A5"
color6="#DA69D2"
color7="#c5c1c4"
color8="#6d5969"
color9="#A6416D"
color10="#69388F"
color11="#993B8C"
color12="#AC4798"
color13="#D154A5"
color14="#DA69D2"
color15="#c5c1c4"
