[colors]
background = '#170a158e'
black = '#170a15'
blue = '#A6416D'
cursor = '#c5c1c4'
cyan = '#69388F'
foreground = '#c5c1c4'
green = '#993B8C'
magenta = '#AC4798'
red = '#D154A5'
tabs = '#c5c1c4'
tabs-active = '#DA69D2'
white = '#c5c1c4'
yellow = '#c5c1c4'
dim-black = '#170a158e'
dim-blue = '#A6416D8e'
dim-cyan = '#69388F8e'
dim-foreground = '#c5c1c48e'
dim-green = '#993B8C8e'
dim-magenta = '#AC47988e'
dim-red = '#D154A58e'
dim-white = '#DA69D28e'
dim-yellow = '#c5c1c48e'
light-black = '#A6416D'
light-blue = '#69388F'
light-cyan = '#993B8C'
light-foreground = '#AC4798'
light-green = '#D154A5'
light-magenta = '#DA69D2'
light-red = '#c5c1c4'
light-white = '#A6416D'
light-yellow = '#69388F'
