require("conf.envs")
require("conf.monitors")
require("conf.autostarts")
require("conf.binds")
require("conf.window_rules")
require("conf.layer_rules")
require("conf.general")
require("conf.decoration")
require("conf.animation")
require("conf.input")
require("conf.misc")

-- require("~/.config/themes/colors.lua")
