hl.on("hyprland.start", function()
    hl.exec_cmd("keyd")
    hl.exec_cmd("hyprpaper & hypridle & hyprsunset & quickshell")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("iwd & iwgtk -i")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("flameshot")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("easyeffects --gapplication-service --quit")
    hl.exec_cmd("rmpc togglerandom && rmpc togglerepeat")
end)
-- hl.exec_cmd("swaync")
