$wallpaper = /home/notscripter/.config/themes/background.jpg

$primary = rgb(216, 144, 52)
$secondary = rgb(194, 171, 144)
$tertiary = rgb(187, 127, 53)
$surface = rgba(0, 0, 0, 0.004)
$onPrimary = rgb(244, 198, 124)
$onSecondary = rgb(244, 198, 124)
$onTertiary = rgb(244, 198, 124)
$onSurface = rgb(244, 198, 124)

$highlight = rgba(255, 255, 255, 0.078)
$radius = 16px
$shadow = 0px 0px 8px 4px #d89034
$transition = all 50ms cubic-bezier(0.85, 0, 0.15, 1)
