$wallpaper = /home/notscripter/.config/themes/background.jpg

$primary = rgb(223, 169, 118)
$secondary = rgb(209, 148, 102)
$tertiary = rgb(194, 127, 85)
$surface = rgba(0, 0, 0, 0.004)
$onPrimary = rgb(249, 242, 206)
$onSecondary = rgb(249, 242, 206)
$onTertiary = rgb(249, 242, 206)
$onSurface = rgb(249, 242, 206)

$highlight = rgba(255, 255, 255, 0.078)
$radius = 16px
$shadow = 0px 0px 8px 4px #dfa976
$transition = all 50ms cubic-bezier(0.85, 0, 0.15, 1)
