$wallpaper = /home/notscripter/.config/themes/background.jpg

$primary = rgb(233, 118, 72)
$secondary = rgb(207, 65, 41)
$tertiary = rgb(178, 46, 27)
$surface = rgba(0, 0, 0, 0.004)
$onPrimary = rgb(243, 210, 150)
$onSecondary = rgb(243, 210, 150)
$onTertiary = rgb(243, 210, 150)
$onSurface = rgb(243, 210, 150)

$highlight = rgba(255, 255, 255, 0.078)
$radius = 16px
$shadow = 0px 0px 8px 4px #e97648
$transition = all 50ms cubic-bezier(0.85, 0, 0.15, 1)
