exec-once = waybar
# exec-once = ashell
exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprsunset
exec-once = swaync
# exec-once = hyprpanel
exec-once = blueman
exec-once = keyd
# exec-once = clipse -listen
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpm reload -n
# exec-once = iwd & iwgtk -i

# exec-once = hyprctl plugin load /home/notscripter/Hyprspace/Hyprspace.so
# exec-once = mount --bind ~/Downloads ~/.local/share/waydroid/data/media/0/Download
# exec-once=walker --gapplication-service

exec-once=easyeffects --gapplication-service --quit
exec-once=rmpc togglerandom && rmpc togglerepeat
