source = ~/.config/themes/colors.conf

decoration {
    rounding = 16
    rounding_power = 2

    blur {
        enabled = true
        size = 0
        passes = 3
        brightness = 0.5
        vibrancy = 0.25
        vibrancy_darkness = 0.25
        ignore_opacity = true
        new_optimizations = true
        xray = true
        popups = true
        popups_ignorealpha = 0.0
        special = true #expensive
        input_methods = true
        input_methods_ignorealpha = 0.0
    }
    shadow {
        enabled = true
        range = 4
        render_power = 2
        color = $primary
        color_inactive = $surface 
    }
}
