source = ~/.config/hypr/akantha.conf

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 0
    col.active_border = $mauve 45deg
    col.inactive_border = $surface0
    layout = dwindle
    # layout = master
    resize_on_border = true
    hover_icon_on_border = true
}
