source = ~/.config/themes/colors.conf

general {
    gaps_in = 2
    gaps_out = 4
    border_size = 0
    # col.active_border = $primary 45deg
    # col.inactive_border = $surface
    # layout = dwindle
    layout = master
    resize_on_border = true
    hover_icon_on_border = true

    allow_tearing = true # windowrule = game:class cs2, immediate yes
}
