layerrule = blur on, match:namespace waybar
layerrule = blur_popups on, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar
layerrule = blur on, match:namespace logout_dialog
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0, match:namespace swaync-control-center
layerrule = ignore_alpha 0, match:namespace swaync-notification-window
layerrule = dim_around on, match:namespace swaync-control-center
layerrule = blur on, match:namespace rofi 
layerrule = ignore_alpha 0, match:namespace rofi
layerrule = dim_around on, match:namespace rofi
