layerrule {
    name = waybar-blur
    blur = on
    blur_popups = on
    ignore_alpha = 0
    match:namespace = waybar
}

layerrule {
    name = wlogout-blur
    blur = on
    match:namespace = logout_dialog
}

layerrule {
    name = swaync-control-center-blur
    blur = on
    ignore_alpha = 0
    dim_around = on
    match:namespace = swaync-control-center
}

layerrule {
    name = swaync-notification-window-blur
    blur = on
    ignore_alpha = 0
    match:namespace = swaync-notification-window
}

layerrule {
    name = rofi-blur
    blur = on
    ignore_alpha = 0
    dim_around = on
    match:namespace = rofi 
}

layerrule {
    name = vicinae-blur
    blur = on
    ignore_alpha = 0
    match:namespace = vicinae
}
