layerrule = blur, waybar
# layerrule = blur, waybar, ignorealpha
# layerrule = ignorezero, waybar
# layerrule = ignorealpha, waybar
# layerrule = xray, waybar

layerrule = blur, logout_dialog
# layerrule = ignorezero, logout_dialog
# layerrule = ignorealpha, logout_dialog

layerrule = blur, swaync-control-center
layerrule = ignorezero, swaync-control-center
# layerrule = ignorealpha, swaync-control-center

layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-notification-window
# layerrule = ignorealpha, swaync-notification-window

layerrule = blur, rofi 
# layerrule = ignorezero, rofi 
# layerrule = ignorealpha, rofi 

# layerrule = blur, class:^(zen)$
# layerrule = ignorezero, class:^(zen)$
layerrule = ignorealpha, class:^(zen)$
