# monitor = , 1920x1080@100, 0x0, 0.75
# monitor = HDMI-A-1, 1920x1080@100, 0x0, 1

monitorv2 {
  # output = auto
  output = HDMI-A-1
  mode = 1920x1080@100
  position = 0x0
  scale = 1
  # transform = 2
  supports_wide_color = 0
  # support_hdr = 0
  sdr_min_luminance = 0.005 #0.005 - 
  sdr_max_luminance = 80 #80 - 400
}
