windowrule = match:title Picture-in-Picture, pin on
windowrule = match:title Picture-in-Picture, float on
windowrule = match:title Picture-in-Picture, move 1532 50
windowrule = match:title Picture-in-Picture, no_initial_focus on
windowrule = match:title Picture-in-Picture, keep_aspect_ratio on

windowrule = match:title File Operation Progress, float on
windowrule = match:title File Operation Progress, size 510 102
windowrule = match:class feh, fullscreen on

windowrule = match:class Postman, float on
windowrule = match:class Postman, size 944 502

windowrule = match:class spotube, float on

windowrule = match:title KiCad, tile on
windowrule = match:title 3D Viewer, maximize on
windowrule = match:class pl_editor, maximize on
windowrule = match:title PCB Editor, maximize on
windowrule = match:title Gerber Viewer, maximize on
windowrule = match:title Symbol Editor, maximize on
windowrule = match:class pcb_calculator, maximize on
windowrule = match:title Image Converter, maximize on
windowrule = match:title Schematic Editor, maximize on
windowrule = match:title Footprint Editor, maximize on
windowrule = match:title Plugin And Content Manager, maximize on

windowrule = match:class scrcpy, keep_aspect_ratio on
windowrule = match:class scrcpy, float on 

windowrule = match:title QtPass, float on
windowrule = match:title QtPass, size 480 600
windowrule = match:title QtPass, no_screen_share on

# windowrule = float,match:class ^(zen-beta)$,match:title ^(Extension: \(Bitwarden Password Manager\))$
windowrule = match:title ^(Developer Tools)*$, float on

windowrule = match:title rmpc, float on
# windowrule = match:class ueberzugpp_*, float on
