windowrule = match:title Picture-in-Picture, pin on
windowrule = match:title Picture-in-Picture, float on
windowrule = match:title Picture-in-Picture, move 1532 50
windowrule = match:title Picture-in-Picture, no_initial_focus on
windowrule = match:title Picture-in-Picture, keep_aspect_ratio on

windowrule = match:title File Operation Progress, float on
windowrule = match:title File Operation Progress, size 510 102
windowrule = match:class feh, fullscreen on

windowrule = match:class Postman, float on
windowrule = match:class Postman, size 944 502
# windowrule = move onscreen cursor -50% -50%, match:class Postman

windowrule = match:class spotube, float on
# windowrule = size 944 502, match:class spotube
# windowrule = move onscreen cursor -50% -50%, match:class spotube

windowrule = match:title KiCad, tile on
windowrule = match:title 3D Viewer, maximize on
windowrule = match:class pl_editor, maximize on
windowrule = match:title PCB Editor, maximize on
windowrule = match:title Gerber Viewer, maximize on
windowrule = match:title Symbol Editor, maximize on
windowrule = match:class pcb_calculator, maximize on
windowrule = match:title Image Converter, maximize on
windowrule = match:title Schematic Editor, maximize on
windowrule = match:title Footprint Editor, maximize on
windowrule = match:title Plugin And Content Manager, maximize on

# windowrule = keepaspectratio, match:class scrcpy
# windowrule = move 1452 54, match:class scrcpy
# windowrule = float, match:class scrcpy
# windowrule = move onscreen cursor -50% -50%, match:class scrcpy

windowrule = match:class scrcpy, keep_aspect_ratio on
windowrule = match:class scrcpy, float on 
# windowrule = move 1610 470, match:class scrcpy
# windowrule = size 300 600, match:title Redmi 6A

windowrule = match:title QtPass, float on
windowrule = match:title QtPass, size 480 600

# windowrule = tag mobile, match:class Waydroid
# windowrule = size 1600 720, tag:mobile

# windowrule = opacity 1, match:title Picture-in-Picture

# windowrule = keepaspectratio, match:class Waydroid
# windowrule = allowsinput, match:class Waydroid
# windowrule = size 458 1016, match:class Waydroid
# windowrule = maxsize 458 1016, match:class Waydroid
# windowrule = move 1452 54, match:class Waydroid
# windowrule = float, match:class Waydroid

# windowrule = float,match:class ^(zen-beta)$,match:title ^(Extension: \(Bitwarden Password Manager\))$
windowrule = match:title ^(Developer Tools)*$, float on


# windowrule = opacity 0.6 0.6, match:class Waydroid
# windowrule = float, match:class Waydroid



# windowrule = float, match:class zen
# windowrule = maxsize 1350 900, match:class zen

windowrule = match:title rmpc, float on
windowrule = match:title rmpc, size 888 512
