windowrule {
    name = pip 
    match:title = Picture-in-Picture

    float = on
    move = 1532 50
    no_initial_focus = on
    keep_aspect_ratio = on
}

windowrule {
    name = file-progress-float
    match:title = File Operation Progress

    float = on
    size = 510 102
}

windowrule {
    name = feh
    match:class = feh

    float = on
}

windowrule {
    name = spotube-float
    match:class = spotube

    float = on
}

windowrule {
    name = scrcpy-float
    match:class = scrcpy

    float = on
    keep_aspect_ratio = on
}

windowrule {
    name = qtpass-float
    match:title = QtPass

    float = on
    no_screen_share = on
}

windowrule {
    name = rmpc-float
    match:title = rmpc

    float = on
}

windowrule {
    name = kicad-tile
    match:title = KiCad

    tile = on
}

windowrule {
    name = devtools-float
    match:title = ^(Developer Tools)*$

    float = on
}

windowrule {
    name = ueberzugpp-float
    match:class = ^(ueberzugpp)(.*)$
    # match:class = ^(ueberzugpp)(.+)$

    float = on
    no_initial_focus = on
}

windowrule {
    name = qtcreator-preview-float
    match:title = ^(Hello World)(.*)$

    float = on
}
