; both are RegExp
tag_start = \^r
tag_end   = \^

; built in script to get wallpaper
; $feh, $nitrogen
imagefile = $feh
; imagefile = $DOTFILES/hypr/background.jpg
; imagefile_script = getmybg

[const]
; you can add variables here
; you can define that like this "@bg"
bg = '@DM>l(15)'
fg = '@V>l(80)'

;here is the configuration for config file that gonna be parsed
[kitty]
filename = kitty.conf
realfilepath = $HOME/.config/kitty/kitty.conf
;
; [i3]
; filename = i3.conf
; realfilepath = /home/fhadiel/.config/i3/config
